### ISSUE TITLE
curve_fit()

### ISSUE THREAD

**Issue by Reegh** [JARA99/F503-2024-public#2]
curve_fit() devuelve valores [1,1] e infinito
![image](https://github.com/JARA99/F503-2024-public/assets/158205399/1d506794-df6a-4f67-99dc-42e70faf4e05)
![image](https://github.com/JARA99/F503-2024-public/assets/158205399/420575a9-005e-49e9-85c8-baeacfa768a5)

**Comment by JARA99** [comment]
Este error está algo feo, resulta que el scipy está evaluando las funciones pasándole una lista de valores de `x` y esperando que retorne una lista de valores de `y` pero en la función que construimos en clase eso no puede ocurrir. Por lo tanto la solución es modificar esta función para que acepte vectores como input. Utilizar la función binomial de scipy tampoco resuelve el error por que ocurre algún error interno en la evaluación de la función que es aún mas difícil de debuggear por que no sabemos como está programada dicha función.

La solución propuesta conlleva la siguiente definición de función binomial:

```python
def binom(x,n,p):
    print('binom(',x,n,p,')')

    if isinstance(x,np.ndarray):
        x = x.astype(int)
    else:
        x = int(x)

    n = int(n)
        
    comb = np.vectorize(math.comb)(n,x)
    p_x = p**x
    q_nx = (1-p)**(n-x)

    return comb*p_x*q_nx
```

Este cambio permite ejecutar el fit, sin embargo será necesario colocar valores iniciales cercanos para que el ajuste no se indetermine. 

También es necesario colocar un **factor de escala**, recuerden que *P_b(x,n)* es un valor de probabilidad entre 0 y 1 mientras que los valores del histograma son conteos de casos, por lo que se deben "normalizar" para que sean valores entre 0 y 1. Esto lo hacemos sencillamente dividiendo el valor del conteo entre el total *m* de casos, por lo que el fit quedaría:

```python
fit, cov_mat = sco.curve_fit(binom,counts.index.values,counts/m,[10,0.5])
```

Pueden ver un ejemplo de todo esto en acción en el archivo [Unidades/2-Distribuciones/fit_example.py](https://github.com/JARA99/F503-2024-public/blob/main/Unidades/2-Distribuciones/fit_example.py)

**Comment by JARA99** [comment]
Hay una forma más elegante de definir la función binomial sin cambiar mucho el código original, esto es usar el código original y luego vectorizarla, ya lo probé y todo va bien con esta metolodogía, por lo que los únicos cambios que deben hacer para que les funcione es asegurarse de usar enteros para `n` y `x` (usando `int(n)` e `int(x)`) y redefinir la función con `np.vectorize`:

```python
def binom(x,n,p):
    
    x = int(x)
    n = int(n)
        
    comb = math.comb(n,x)
    p_x = p**x
    q_nx = (1-p)**(n-x)

    return comb*p_x*q_nx

binom = np.vectorize(binom)
```

**Comment by JARA99** [comment]
Por otro lado, hay un aproximación a este fit totalmente distinta pero igual válida. Pueden utilizar [`scipy.stats.bionom`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom.html) pero solo si usan [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html).

Este es mas rápido de programar por que no deben hacer los conteos de casos sino solo pasarle toda la distribución y el resto lo hace la misma función. Lo único que si deben hacer es pasarle una lista de 'contornos' en donde los valores del fit pueden estar, puede ser 0<=n<=100 y 0<=x<=1 por ejemplo.

```python
import pandas as pd
from matplotlib import pyplot as plt
from scipy import stats as ss

m = 100

data = pd.read_csv('Binomial-fichas.csv')
data = data.loc[:m,'GM']
print(f'data:\n{data}')

fitted_results = ss.fit(ss.binom,data,bounds=[(0,100),(0,1)])
print(fitted_results)
```

Les dejo el ejemplo de código completo [aquí](https://github.com/JARA99/F503-2024-public/blob/main/Unidades/2-Distribuciones/fit_example2.py).

**Comment by Reegh** [comment]
Se creó una función que aceptara los datos medidos y los convirtiera en int:
```python
def fit_function(x,n,p):

    n = int(n)
    x = np.array(x, dtype=int)
    combi = comb(n,x)
    px = p**x
    qnx = (1-p)**(n-x)
    return combi*px*qnx
```
Para ajustar el fit se colocaron valores iniciales apropiados para la distribución:
```python
p0=[10,1/2]
res, cov = curve_fit(fit_function, value_range, group_2, p0=p0, bounds=[(0,0), (np.inf,1)])
```
Finalmente en la gráfica se colocó un factor de escala para que el fit se muestre sobre los datos graficados
```python
binomial = px.line(x=value_range, y=fit_function(value_range, *res)*number)
binomial.add_bar(x=group['GM'], y=group['count'], name='binomial')
```
Con esto se obtuvo el fit y se arregló el problema de los valores de covarianza infinitos.
