### ISSUE TITLE
Desaparecio mi carpeta de Ubuntu :(

### ISSUE THREAD

**Issue by DiegoChew** [JARA99/F503-2024-public#3]
No aparecen las carpetas del WSL aun buscando los archivos no los logran encontar, pero vs code si puede abrirlos, ejecutarlos e incluso actulizar mi repositorio en github. Pero no me aparece ninguna distribución de linux en la parte izquierda a la hora de abrir el explorador de archivos

**Comment by JARA99** [comment]
Podrías intentar usar esto: [https://thegeekpage.com/how-to-add-or-remove-linux-in-file-explorer-navigation-pane-on-windows-11/](https://thegeekpage.com/how-to-add-or-remove-linux-in-file-explorer-navigation-pane-on-windows-11/)

**Comment by DiegoChew** [comment]
Segui todo y segun se realizaron los cambios pero nada
